import type { ComponentType, SVGProps } from "react";
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeAlert,
  BadgeCheck,
  Ban,
  Bell,
  BellRing,
  Bot,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  CirclePlay,
  Clock,
  Clock3,
  Coins,
  Copy,
  Crown,
  Download,
  DollarSign,
  Eye,
  EyeOff,
  ExternalLink,
  FileCheck2,
  Flame,
  Gauge,
  Globe,
  Github,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Link2,
  Loader,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Percent,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Save,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Target,
  Terminal,
  ToggleLeft,
  ToggleRight,
  Trash2,
  Trophy,
  TrendingDown,
  TrendingUp,
  Twitter,
  Unlink,
  User,
  Users,
  Wallet,
  Workflow,
  X,
  Zap,
} from "lucide-react";

type LucideProps = SVGProps<SVGSVGElement> & {
  size?: number | string;
  color?: string;
  absoluteStrokeWidth?: boolean;
};

function stub(Alt: ComponentType<LucideProps>): ComponentType<LucideProps> {
  return function PolyfillIcon(props: LucideProps) {
    return <Alt {...props} />;
  };
}

export {
  Activity,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeAlert,
  BadgeCheck,
  Ban,
  Bell,
  BellRing,
  Bot,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  CirclePlay,
  Clock,
  Clock3,
  Coins,
  Copy,
  Crown,
  Download,
  DollarSign,
  Eye,
  EyeOff,
  ExternalLink,
  FileCheck2,
  Flame,
  Gauge,
  Globe,
  Github,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  Link2,
  Loader,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Percent,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Save,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Target,
  Terminal,
  ToggleLeft,
  ToggleRight,
  Trash2,
  Trophy,
  TrendingDown,
  TrendingUp,
  Twitter,
  Unlink,
  User,
  Users,
  Wallet,
  Workflow,
  X,
  Zap,
};

export const Globe2: ComponentType<LucideProps> = stub(Globe);
export const BarChart3: ComponentType<LucideProps> = stub(Activity);
export const LineChart: ComponentType<LucideProps> = stub(Activity);
export const Code2: ComponentType<LucideProps> = stub(Terminal);
export const UserCircle2: ComponentType<LucideProps> = stub(User);
export const CheckCircle2: ComponentType<LucideProps> = stub(BadgeCheck);
export const AlertTriangle: ComponentType<LucideProps> = stub(ShieldAlert);
export const PlusCircle: ComponentType<LucideProps> = stub(Plus);
export const Edit3: ComponentType<LucideProps> = stub(Settings2);
export const XCircle: ComponentType<LucideProps> = stub(Ban);
export const PlayCircle: ComponentType<LucideProps> = stub(CirclePlay);
export const Loader2: ComponentType<LucideProps> = stub(Loader);
export const BarChart4: ComponentType<LucideProps> = stub(Activity);
export const BarChart: ComponentType<LucideProps> = stub(Activity);
export const AlertOctagon: ComponentType<LucideProps> = stub(ShieldAlert);
export const Unlink2: ComponentType<LucideProps> = stub(Unlink);
